services:
  api:
    build: .
    container_name: job_portal_api

    ports:
      - "8000:8000"

    env_file:
      - .env
      
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0

    container_name: mysql_db
    helathcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval:10s
      timeout:5s
      retries:5


    environment:
      MYSQL_ROOT_PASSWORD: vishnu123456
      MYSQL_DATABASE: linkedin

    ports:
      - "3307:3306"